version: "3.9"
services:
  backend:
    build:
      context: ./backend-pokemon-app
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend-pokemon-app
    ports:
      - "3000:3000"
