version: '3'
services:
  flask-app:
    container_name: service-flask-app
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    ports:
      - "8000:8000"
    networks:
      - flask
  consumer-python:
    container_name: consumer-python
    build:
      context: ./consumer
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    environment:
      LOCAL: "true"
    networks:
      - flask
networks:
  flask:
    driver: bridge
