version: '3'
services:
  flask-app:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile
      args:
        APP_VERSION: 1.0.0
    container_name: service-flask-app
    ports:
      - "8000:8000"
    networks:
      - flask
  consumer-python:
    build:
      context: ./consumer
      dockerfile: ./consumer/Dockerfile
      args:
        APP_VERSION: 1.0.0
    container_name: consumer-python
    environment:
      LOCAL: "true"
    networks:
      - flask

networks:
  flask:
    driver: bridge
