# version: '3'

# services:
#   myapp:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     restart: always

# version: '3'

# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - flask

networks:
  flask:
    driver: bridge


