version: '3'
services:
  app:
    container_name: guestbook
    image: roxsross12/guestbook
    restart: always
    ports:
      - 80:5000
    depends_on:
      - redis
    networks:
      - net_guestbook

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6376:6376
    networks:
      - net_guestbook

networks:
  net_guestbook:
    driver: bridge